Repository RecruitUs/Wanted-Server, pull requests merged in 2023-08, with the labels that each got.

#18 Feat/#14 user update delete
  src/main/java/com/example/rcp1/domain/user/application/UserService.java
  src/main/java/com/example/rcp1/domain/user/domain/User.java
  src/main/java/com/example/rcp1/domain/user/dto/UpdateProfileReq.java
  src/main/java/com/example/rcp1/domain/user/presentation/UserController.java
  src/main/java/com/example/rcp1/global/SuccessCode.java
  src/main/java/com/example/rcp1/global/config/security/JwtFilter.java
  src/main/java/com/example/rcp1/global/config/security/SecurityConfig.java
Labels: feature

#20 [FEAT]#16 좋아요 기능 구현완료(채용공고 구현 완료 시 연결, Response 수정필요)
  src/main/java/com/example/rcp1/domain/heart/application/HeartService.java
  src/main/java/com/example/rcp1/domain/heart/domain/Heart.java
  src/main/java/com/example/rcp1/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/example/rcp1/domain/heart/dto/HeartReq.java
  src/main/java/com/example/rcp1/domain/heart/presentation/HeartController.java
  src/main/java/com/example/rcp1/domain/user/application/UserService.java
  src/main/java/com/example/rcp1/domain/user/domain/User.java
  src/main/java/com/example/rcp1/domain/user/dto/SignUpReq.java
  src/main/java/com/example/rcp1/global/config/security/SecurityConfig.java
Labels: feature

#22 Feat/#7 recruiting post creation
  src/main/java/com/example/rcp1/domain/recruitment/application/RecruitmentService.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/Field.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/Post.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/repository/FieldRepository.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/repository/PostRepository.java
  src/main/java/com/example/rcp1/domain/recruitment/dto/FieldDTO.java
  src/main/java/com/example/rcp1/domain/recruitment/dto/PostDTO.java
  src/main/java/com/example/rcp1/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/com/example/rcp1/global/SuccessCode.java
Labels: feature, fix

#24 [FIX]#23 연관관계 매핑 수정
  src/main/java/com/example/rcp1/domain/heart/application/HeartService.java
  src/main/java/com/example/rcp1/domain/heart/domain/Heart.java
  src/main/java/com/example/rcp1/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/example/rcp1/global/config/security/util/JwtUtil.java
Labels: fix

#26 [FEAT]#21 특정 채용에 지원 기능 구현
  src/main/java/com/example/rcp1/domain/applying/application/ApplyingService.java
  src/main/java/com/example/rcp1/domain/applying/domain/Applying.java
  src/main/java/com/example/rcp1/domain/applying/domain/repository/ApplyingRepository.java
  src/main/java/com/example/rcp1/domain/applying/dto/ApplyReq.java
  src/main/java/com/example/rcp1/domain/applying/presentation/ApplyingController.java
  src/main/java/com/example/rcp1/global/SuccessCode.java
  src/main/java/com/example/rcp1/global/config/security/SecurityConfig.java
Labels: feature

#27 [FEAT]#25 채용공고 조회 기능 구현
  build.gradle
  src/main/java/com/example/rcp1/domain/recruitment/application/RecruitmentService.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/repository/PostRepository.java
  src/main/java/com/example/rcp1/domain/recruitment/dto/PostReqDTO.java
  src/main/java/com/example/rcp1/domain/recruitment/dto/PostResDTO.java
  src/main/java/com/example/rcp1/domain/recruitment/presentation/RecruitmentController.java
  src/main/java/com/example/rcp1/global/ErrorCode.java
  src/main/java/com/example/rcp1/global/SuccessCode.java
Labels: feature

#29 Feat/#21 applying
  src/main/java/com/example/rcp1/domain/applying/application/ApplyingService.java
  src/main/java/com/example/rcp1/domain/applying/domain/Applying.java
  src/main/java/com/example/rcp1/domain/applying/domain/repository/ApplyingRepository.java
  src/main/java/com/example/rcp1/domain/applying/dto/GetStatusRes.java
  src/main/java/com/example/rcp1/domain/applying/dto/SetResultReq.java
  src/main/java/com/example/rcp1/domain/applying/presentation/ApplyingController.java
  src/main/java/com/example/rcp1/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/rcp1/global/SuccessCode.java
Labels: feature

#35 [FEAT]#34 채용공고 삭제 기능 구현
  src/main/java/com/example/rcp1/domain/recruitment/application/RecruitmentService.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/repository/PostRepository.java
  src/main/java/com/example/rcp1/domain/recruitment/presentation/RecruitmentController.java
Labels: feature, refactor

#37 [FEAT]#36 채용공고 조회시 좋아요 조회기능 추가
  src/main/java/com/example/rcp1/domain/heart/application/HeartService.java
  src/main/java/com/example/rcp1/domain/heart/domain/Heart.java
  src/main/java/com/example/rcp1/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/example/rcp1/domain/recruitment/application/RecruitmentService.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/Field.java
  src/main/java/com/example/rcp1/domain/recruitment/domain/Post.java
  src/main/java/com/example/rcp1/domain/recruitment/dto/PostReqDTO.java
  src/main/java/com/example/rcp1/domain/recruitment/dto/PostResDTO.java
Labels: feature, refactor
